vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
            cars:
                uri_prefix: /media/photos
                upload_destination: media/photos
                namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
                directory_namer:
                    service: vich_uploader.namer_directory_property
                    options: { property: 'car.licensePlate', transliterate: true }

            services:
                uri_prefix: /media/photos/service
                upload_destination: media/photos/service/
                namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
#                    service: Vich\UploaderBundle\Naming\PropertyNamer
#                    options: {property: 'name'}
#                directory_namer:
#                    service: vich_uploader.namer_directory_property
#                    options: { property: 'name', transliterate: true }
