vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
            cars:
                uri_prefix: /media/photos
                upload_destination: media/photos
                namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
                directory_namer:
                    service: vich_uploader.namer_directory_property
                    options: { property: 'car.licensePlate' }
            services:
                uri_prefix: /media/photos/services
                upload_destination: media/photos/services/
                namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

