vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        cars:
            uri_prefix: /images/cars
            upload_destination: '%kernel.project_dir%/public/build/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
